<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net461</TargetFramework>
        <RootNamespace>RPA_Parser</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="WebPWrapper.cs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Ionic.Zlib" Version="1.9.1.5" />
      <PackageReference Include="Razorvine.Pickle" Version="1.2.1" />
    </ItemGroup>

</Project>
