<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <Platforms>x64</Platforms>
    <AssemblyTitle>RPA Explorer</AssemblyTitle>
    <VersionPrefix>1.1.0</VersionPrefix>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    <Authors>UniverseDevel, TwelveBaud</Authors>
    <Copyright>Copyright ©2022-2026 Martin Suchy, Andrew Cook</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/TwelveBaud/RPA-Explorer</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Link="README.md">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp" Version="3.9.7" />
    <PackageReference Include="LibVLCSharp.WinForms" Version="3.9.7" />
    <PackageReference Include="System.Memory" Version="4.6.0" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RPA Explorer\RPA Explorer.csproj" />
  </ItemGroup>

</Project>
