<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <Platforms>x64</Platforms>
    <AssemblyTitle>RPA Explorer</AssemblyTitle>
    <VersionPrefix>1.1.0</VersionPrefix>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    <Authors>UniverseDevel, TwelveBaud</Authors>
    <Copyright>Copyright ©2022-2026 Martin Suchy, Andrew Cook</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/TwelveBaud/RPA-Explorer</RepositoryUrl>
  </PropertyGroup>

  <PropertyGroup>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="aom.dll" />
    <None Remove="libde265.dll" />
    <None Remove="libheif.dll" />
    <None Remove="libwebp_x64.dll" />
    <None Remove="libx265.dll" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="aom.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="libde265.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="libheif.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="libwebp_x64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="libx265.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Link="README.md">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibHeifSharp" Version="3.2.0" />
    <PackageReference Include="System.Memory" Version="4.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RPA Explorer\RPA Explorer.csproj" />
  </ItemGroup>
</Project>
