<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <Platforms>x64</Platforms>
    <AssemblyTitle>RPA Explorer</AssemblyTitle>
    <VersionPrefix>1.1.0</VersionPrefix>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    <Authors>UniverseDevel, TwelveBaud</Authors>
    <Copyright>Copyright ©2022-2026 Martin Suchy, Andrew Cook</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/TwelveBaud/RPA-Explorer</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Link="README.md">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Razorvine.Pickle" Version="1.2.1" />
    <PackageReference Include="System.IO.Compression" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RPA Explorer\RPA Explorer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Lang.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Lang.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Lang.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Lang.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
