//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code.previewer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Code.previewer.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To preview compiled Ren&apos;Py scripts, you need a copy of Python and a copy of the Unrpyc decompiler by CensoredUsername.
        /// </summary>
        internal static string Configuration_Description {
            get {
                return ResourceManager.GetString("Configuration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use these settings.
        /// </summary>
        internal static string Configuration_Exit {
            get {
                return ResourceManager.GetString("Configuration_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❮❮not available❯❯.
        /// </summary>
        internal static string Configuration_NotAvailable {
            get {
                return ResourceManager.GetString("Configuration_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❮❮not set❯❯.
        /// </summary>
        internal static string Configuration_NotSet {
            get {
                return ResourceManager.GetString("Configuration_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string Configuration_Python_BrowseButton {
            get {
                return ResourceManager.GetString("Configuration_Python_BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another copy of Python.
        /// </summary>
        internal static string Configuration_Python_BrowseLabel {
            get {
                return ResourceManager.GetString("Configuration_Python_BrowseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python: {0}.
        /// </summary>
        internal static string Configuration_Python_CurrentVersion {
            get {
                return ResourceManager.GetString("Configuration_Python_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a copy of Python.
        /// </summary>
        internal static string Configuration_Python_Download {
            get {
                return ResourceManager.GetString("Configuration_Python_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0}.
        /// </summary>
        internal static string Configuration_Python_Pep514 {
            get {
                return ResourceManager.GetString("Configuration_Python_Pep514", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be aware that earlier games require Python 2 and Unrpyc 1, while later games require Python 3 and Unrpyc 2..
        /// </summary>
        internal static string Configuration_Reminder {
            get {
                return ResourceManager.GetString("Configuration_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrpyc Configuration.
        /// </summary>
        internal static string Configuration_Title {
            get {
                return ResourceManager.GetString("Configuration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string Configuration_Unrpyc_BrowseButton {
            get {
                return ResourceManager.GetString("Configuration_Unrpyc_BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Configuration_Unrpyc_Download {
            get {
                return ResourceManager.GetString("Configuration_Unrpyc_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrpyc: {0}.
        /// </summary>
        internal static string Configuration_Unrypc_CurrentVersion {
            get {
                return ResourceManager.GetString("Configuration_Unrypc_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting Python {0}....
        /// </summary>
        internal static string Download_Python_Extracting {
            get {
                return ResourceManager.GetString("Download_Python_Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Python {0}....
        /// </summary>
        internal static string Download_Python_Fetching {
            get {
                return ResourceManager.GetString("Download_Python_Fetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting available Python versions....
        /// </summary>
        internal static string Download_Python_WhichPython {
            get {
                return ResourceManager.GetString("Download_Python_WhichPython", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting Unrpyc {0}....
        /// </summary>
        internal static string Download_Unrpyc_Extracting {
            get {
                return ResourceManager.GetString("Download_Unrpyc_Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Unrpyc {0}....
        /// </summary>
        internal static string Download_Unrpyc_Fetching {
            get {
                return ResourceManager.GetString("Download_Unrpyc_Fetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting Python version....
        /// </summary>
        internal static string Download_Unrypc_WhichPython {
            get {
                return ResourceManager.GetString("Download_Unrypc_WhichPython", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting available Unrpyc versions....
        /// </summary>
        internal static string Download_Unrypc_WhichUnrpyc {
            get {
                return ResourceManager.GetString("Download_Unrypc_WhichUnrpyc", resourceCulture);
            }
        }
    }
}
