//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPA_Explorer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPA_Explorer.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martin Suchy.
        /// </summary>
        internal static string _Translator {
            get {
                return ResourceManager.GetString("!Translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string About_close {
            get {
                return ResourceManager.GetString("About_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors credits.
        /// </summary>
        internal static string About_contributors {
            get {
                return ResourceManager.GetString("About_contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Martin &quot;UniverseDevel&quot; Suchy.
        /// </summary>
        internal static string About_creators {
            get {
                return ResourceManager.GetString("About_creators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclosures.
        /// </summary>
        internal static string About_disclosures {
            get {
                return ResourceManager.GetString("About_disclosures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspired by rpatool and unrpyc..
        /// </summary>
        internal static string About_inspiration {
            get {
                return ResourceManager.GetString("About_inspiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations credits.
        /// </summary>
        internal static string About_translations {
            get {
                return ResourceManager.GetString("About_translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version {0}.
        /// </summary>
        internal static string About_version {
            get {
                return ResourceManager.GetString("About_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive location: .
        /// </summary>
        internal static string Archive_file_location {
            get {
                return ResourceManager.GetString("Archive_file_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive size: .
        /// </summary>
        internal static string Archive_file_size {
            get {
                return ResourceManager.GetString("Archive_file_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive modified.
        /// </summary>
        internal static string Archive_modified {
            get {
                return ResourceManager.GetString("Archive_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive was modified, do you really want to exit without saving and lose changes?.
        /// </summary>
        internal static string Archive_modified_close {
            get {
                return ResourceManager.GetString("Archive_modified_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive was modified, do you really want to load a new one and lose changes?.
        /// </summary>
        internal static string Archive_modified_load {
            get {
                return ResourceManager.GetString("Archive_modified_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive was modified, do you really want to create a new one and lose changes?.
        /// </summary>
        internal static string Archive_modified_new {
            get {
                return ResourceManager.GetString("Archive_modified_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Archive_save_cancel {
            get {
                return ResourceManager.GetString("Archive_save_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Archive_save_continue {
            get {
                return ResourceManager.GetString("Archive_save_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obfuscation key:.
        /// </summary>
        internal static string Archive_save_obfuscationkey {
            get {
                return ResourceManager.GetString("Archive_save_obfuscationkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data padding:.
        /// </summary>
        internal static string Archive_save_padding {
            get {
                return ResourceManager.GetString("Archive_save_padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive options.
        /// </summary>
        internal static string Archive_save_title {
            get {
                return ResourceManager.GetString("Archive_save_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive version:.
        /// </summary>
        internal static string Archive_save_version {
            get {
                return ResourceManager.GetString("Archive_save_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive version: .
        /// </summary>
        internal static string Archive_version {
            get {
                return ResourceManager.GetString("Archive_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel operation.
        /// </summary>
        internal static string Cancel_operation {
            get {
                return ResourceManager.GetString("Cancel_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked files count: .
        /// </summary>
        internal static string Checked_files_count {
            get {
                return ResourceManager.GetString("Checked_files_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked files size: .
        /// </summary>
        internal static string Checked_files_size {
            get {
                return ResourceManager.GetString("Checked_files_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new archive.
        /// </summary>
        internal static string Create_new_archive {
            get {
                return ResourceManager.GetString("Create_new_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty archive.
        /// </summary>
        internal static string Empty_archive {
            get {
                return ResourceManager.GetString("Empty_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive does not contain any files, cannot save empty archive..
        /// </summary>
        internal static string Empty_archive_save {
            get {
                return ResourceManager.GetString("Empty_archive_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RenPy Archive Explorer.
        /// </summary>
        internal static string Explorer_title {
            get {
                return ResourceManager.GetString("Explorer_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export checked.
        /// </summary>
        internal static string Export_checked {
            get {
                return ResourceManager.GetString("Export_checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting file: .
        /// </summary>
        internal static string Exporting_file {
            get {
                return ResourceManager.GetString("Exporting_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate RPA/RPI extensions.
        /// </summary>
        internal static string File_association {
            get {
                return ResourceManager.GetString("File_association", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File exists in archive.
        /// </summary>
        internal static string File_exists {
            get {
                return ResourceManager.GetString("File_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File list:.
        /// </summary>
        internal static string File_list {
            get {
                return ResourceManager.GetString("File_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files count: .
        /// </summary>
        internal static string Files_count {
            get {
                return ResourceManager.GetString("Files_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index file location: .
        /// </summary>
        internal static string Index_file_location {
            get {
                return ResourceManager.GetString("Index_file_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index file size: .
        /// </summary>
        internal static string Index_file_size {
            get {
                return ResourceManager.GetString("Index_file_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid values.
        /// </summary>
        internal static string Invalid_values {
            get {
                return ResourceManager.GetString("Invalid_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langauge:.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive loading failed.
        /// </summary>
        internal static string Load_failed {
            get {
                return ResourceManager.GetString("Load_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading archive failed with following error: {0}.
        /// </summary>
        internal static string Load_failed_reason {
            get {
                return ResourceManager.GetString("Load_failed_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load file.
        /// </summary>
        internal static string Load_file {
            get {
                return ResourceManager.GetString("Load_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load RenPy Archive.
        /// </summary>
        internal static string Load_RenPy_Archive {
            get {
                return ResourceManager.GetString("Load_RenPy_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading additional previewers....
        /// </summary>
        internal static string Loading_additional_previewers {
            get {
                return ResourceManager.GetString("Loading_additional_previewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file: .
        /// </summary>
        internal static string Loading_file {
            get {
                return ResourceManager.GetString("Loading_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Python 2.7 location.
        /// </summary>
        internal static string Locate_python {
            get {
                return ResourceManager.GetString("Locate_python", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate Python interpreter.
        /// </summary>
        internal static string Locate_Python_Interpreter {
            get {
                return ResourceManager.GetString("Locate_Python_Interpreter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define unrpyc location.
        /// </summary>
        internal static string Locate_unrpyc {
            get {
                return ResourceManager.GetString("Locate_unrpyc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate unrpyc script.
        /// </summary>
        internal static string Locate_unrpyc_script {
            get {
                return ResourceManager.GetString("Locate_unrpyc_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        internal static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file is not valid archive file..
        /// </summary>
        internal static string Not_valid_archive_file {
            get {
                return ResourceManager.GetString("Not_valid_archive_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview load failed.
        /// </summary>
        internal static string Preview_failed {
            get {
                return ResourceManager.GetString("Preview_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading preview failed with following error: {0}.
        /// </summary>
        internal static string Preview_failed_reason {
            get {
                return ResourceManager.GetString("Preview_failed_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading preview failed with error: {0} Use &apos;Options&apos; to define external locations for this preview..
        /// </summary>
        internal static string Preview_failed_reason_hint {
            get {
                return ResourceManager.GetString("Preview_failed_reason_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview is not supported for selected file/folder..
        /// </summary>
        internal static string Preview_is_not_supported {
            get {
                return ResourceManager.GetString("Preview_is_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python interpreter.
        /// </summary>
        internal static string Python_interpreter {
            get {
                return ResourceManager.GetString("Python_interpreter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove checked.
        /// </summary>
        internal static string Remove_checked {
            get {
                return ResourceManager.GetString("Remove_checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; exists in archive, do you want to replace it?.
        /// </summary>
        internal static string Replace_file {
            get {
                return ResourceManager.GetString("Replace_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPA/RPI files.
        /// </summary>
        internal static string RPA_RPI_files {
            get {
                return ResourceManager.GetString("RPA_RPI_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save archive.
        /// </summary>
        internal static string Save_archive {
            get {
                return ResourceManager.GetString("Save_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed.
        /// </summary>
        internal static string Save_failed {
            get {
                return ResourceManager.GetString("Save_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving new archive failed with following error: {0}.
        /// </summary>
        internal static string Save_failed_reason {
            get {
                return ResourceManager.GetString("Save_failed_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save RenPy Archive.
        /// </summary>
        internal static string Save_RenPy_Archive {
            get {
                return ResourceManager.GetString("Save_RenPy_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving archive....
        /// </summary>
        internal static string Saving_archive {
            get {
                return ResourceManager.GetString("Saving_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search next.
        /// </summary>
        internal static string Search_next {
            get {
                return ResourceManager.GetString("Search_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file path: .
        /// </summary>
        internal static string Selected_file_path {
            get {
                return ResourceManager.GetString("Selected_file_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file size: .
        /// </summary>
        internal static string Selected_file_size {
            get {
                return ResourceManager.GetString("Selected_file_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unrpyc script.
        /// </summary>
        internal static string UNRPYC_script {
            get {
                return ResourceManager.GetString("UNRPYC_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved files count: .
        /// </summary>
        internal static string Unsaved_files_count {
            get {
                return ResourceManager.GetString("Unsaved_files_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file from file list on the side to preview contents. Check and export to save it locally or delete it from archive. Drag and drop files to file list to add new files into archive..
        /// </summary>
        internal static string Usage_instructions_loaded {
            get {
                return ResourceManager.GetString("Usage_instructions_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start by creating/loading archive file or drag and drop archive file into this area to load it..
        /// </summary>
        internal static string Usage_instructions_new {
            get {
                return ResourceManager.GetString("Usage_instructions_new", resourceCulture);
            }
        }
    }
}
