//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPA_Explorer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPA_Explorer.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martin Suchy.
        /// </summary>
        public static string _Translator {
            get {
                return ResourceManager.GetString("!Translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string About_close {
            get {
                return ResourceManager.GetString("About_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit {0}.
        /// </summary>
        public static string About_commit {
            get {
                return ResourceManager.GetString("About_commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors credits.
        /// </summary>
        public static string About_contributors {
            get {
                return ResourceManager.GetString("About_contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Martin &quot;UniverseDevel&quot; Suchy.
        /// </summary>
        public static string About_creators {
            get {
                return ResourceManager.GetString("About_creators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclosures.
        /// </summary>
        public static string About_disclosures {
            get {
                return ResourceManager.GetString("About_disclosures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspired by rpatool and unrpyc..
        /// </summary>
        public static string About_inspiration {
            get {
                return ResourceManager.GetString("About_inspiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations credits.
        /// </summary>
        public static string About_translations {
            get {
                return ResourceManager.GetString("About_translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version {0}.
        /// </summary>
        public static string About_version {
            get {
                return ResourceManager.GetString("About_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive location: .
        /// </summary>
        public static string Archive_file_location {
            get {
                return ResourceManager.GetString("Archive_file_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive size: .
        /// </summary>
        public static string Archive_file_size {
            get {
                return ResourceManager.GetString("Archive_file_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive modified.
        /// </summary>
        public static string Archive_modified {
            get {
                return ResourceManager.GetString("Archive_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive was modified, do you really want to exit without saving and lose changes?.
        /// </summary>
        public static string Archive_modified_close {
            get {
                return ResourceManager.GetString("Archive_modified_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive was modified, do you really want to load a new one and lose changes?.
        /// </summary>
        public static string Archive_modified_load {
            get {
                return ResourceManager.GetString("Archive_modified_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive was modified, do you really want to create a new one and lose changes?.
        /// </summary>
        public static string Archive_modified_new {
            get {
                return ResourceManager.GetString("Archive_modified_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Archive_save_cancel {
            get {
                return ResourceManager.GetString("Archive_save_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Archive_save_continue {
            get {
                return ResourceManager.GetString("Archive_save_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obfuscation key:.
        /// </summary>
        public static string Archive_save_obfuscationkey {
            get {
                return ResourceManager.GetString("Archive_save_obfuscationkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data padding:.
        /// </summary>
        public static string Archive_save_padding {
            get {
                return ResourceManager.GetString("Archive_save_padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive options.
        /// </summary>
        public static string Archive_save_title {
            get {
                return ResourceManager.GetString("Archive_save_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive version:.
        /// </summary>
        public static string Archive_save_version {
            get {
                return ResourceManager.GetString("Archive_save_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive version: .
        /// </summary>
        public static string Archive_version {
            get {
                return ResourceManager.GetString("Archive_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel operation.
        /// </summary>
        public static string Cancel_operation {
            get {
                return ResourceManager.GetString("Cancel_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked files count: .
        /// </summary>
        public static string Checked_files_count {
            get {
                return ResourceManager.GetString("Checked_files_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked files size: .
        /// </summary>
        public static string Checked_files_size {
            get {
                return ResourceManager.GetString("Checked_files_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new archive.
        /// </summary>
        public static string Create_new_archive {
            get {
                return ResourceManager.GetString("Create_new_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty archive.
        /// </summary>
        public static string Empty_archive {
            get {
                return ResourceManager.GetString("Empty_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive does not contain any files, cannot save empty archive..
        /// </summary>
        public static string Empty_archive_save {
            get {
                return ResourceManager.GetString("Empty_archive_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RenPy Archive Explorer.
        /// </summary>
        public static string Explorer_title {
            get {
                return ResourceManager.GetString("Explorer_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export checked.
        /// </summary>
        public static string Export_checked {
            get {
                return ResourceManager.GetString("Export_checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting file: .
        /// </summary>
        public static string Exporting_file {
            get {
                return ResourceManager.GetString("Exporting_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate RPA/RPI extensions.
        /// </summary>
        public static string File_association {
            get {
                return ResourceManager.GetString("File_association", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File exists in archive.
        /// </summary>
        public static string File_exists {
            get {
                return ResourceManager.GetString("File_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File list:.
        /// </summary>
        public static string File_list {
            get {
                return ResourceManager.GetString("File_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files count: .
        /// </summary>
        public static string Files_count {
            get {
                return ResourceManager.GetString("Files_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index file location: .
        /// </summary>
        public static string Index_file_location {
            get {
                return ResourceManager.GetString("Index_file_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index file size: .
        /// </summary>
        public static string Index_file_size {
            get {
                return ResourceManager.GetString("Index_file_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid values.
        /// </summary>
        public static string Invalid_values {
            get {
                return ResourceManager.GetString("Invalid_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langauge:.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive loading failed.
        /// </summary>
        public static string Load_failed {
            get {
                return ResourceManager.GetString("Load_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading archive failed with following error: {0}.
        /// </summary>
        public static string Load_failed_reason {
            get {
                return ResourceManager.GetString("Load_failed_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load file.
        /// </summary>
        public static string Load_file {
            get {
                return ResourceManager.GetString("Load_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load RenPy Archive.
        /// </summary>
        public static string Load_RenPy_Archive {
            get {
                return ResourceManager.GetString("Load_RenPy_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading additional previewers....
        /// </summary>
        public static string Loading_additional_previewers {
            get {
                return ResourceManager.GetString("Loading_additional_previewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file: .
        /// </summary>
        public static string Loading_file {
            get {
                return ResourceManager.GetString("Loading_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string MediaStub_Download {
            get {
                return ResourceManager.GetString("MediaStub_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for media support files.
        /// </summary>
        public static string MediaStub_Download_checking {
            get {
                return ResourceManager.GetString("MediaStub_Download_checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previewing media has been separated into a support package in this version of RPA Explorer.
        ///This saved 100MB off the initial download and 10-30 seconds off each startup.
        ///
        ///To preview this file, you&apos;ll need to download that support package and add its files to RPA Explorer.
        ///Check the &quot;Releases&quot; section of GitHub (link in the About screen) or use the button below.
        ///
        ///RPA Explorer will need to be restarted for this to take effect..
        /// </summary>
        public static string MediaStub_Download_explained {
            get {
                return ResourceManager.GetString("MediaStub_Download_explained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download required.
        /// </summary>
        public static string MediaStub_Download_required {
            get {
                return ResourceManager.GetString("MediaStub_Download_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}.
        /// </summary>
        public static string MediaStub_Downloading_file {
            get {
                return ResourceManager.GetString("MediaStub_Downloading_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting media support files.
        /// </summary>
        public static string MediaStub_Extracting {
            get {
                return ResourceManager.GetString("MediaStub_Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The media support package has been successfully extracted.
        ///
        ///Please restart RPA Explorer for it to take effect..
        /// </summary>
        public static string MediaStub_Restart_required {
            get {
                return ResourceManager.GetString("MediaStub_Restart_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file is not valid archive file..
        /// </summary>
        public static string Not_valid_archive_file {
            get {
                return ResourceManager.GetString("Not_valid_archive_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quick brown fox jumps over the lazy dog..
        /// </summary>
        public static string Pangram_0 {
            get {
                return ResourceManager.GetString("Pangram_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jackdaws love my big sphinx of quartz..
        /// </summary>
        public static string Pangram_1 {
            get {
                return ResourceManager.GetString("Pangram_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The five boxing wizards jump quickly..
        /// </summary>
        public static string Pangram_2 {
            get {
                return ResourceManager.GetString("Pangram_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview load failed.
        /// </summary>
        public static string Preview_failed {
            get {
                return ResourceManager.GetString("Preview_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading preview failed with following error: {0}.
        /// </summary>
        public static string Preview_failed_reason {
            get {
                return ResourceManager.GetString("Preview_failed_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading preview failed with error: {0} Use &apos;Options&apos; to define external locations for this preview..
        /// </summary>
        public static string Preview_failed_reason_hint {
            get {
                return ResourceManager.GetString("Preview_failed_reason_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview is not supported for selected file/folder..
        /// </summary>
        public static string Preview_is_not_supported {
            get {
                return ResourceManager.GetString("Preview_is_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python interpreter.
        /// </summary>
        public static string Python_interpreter {
            get {
                return ResourceManager.GetString("Python_interpreter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove checked.
        /// </summary>
        public static string Remove_checked {
            get {
                return ResourceManager.GetString("Remove_checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; exists in archive, do you want to replace it?.
        /// </summary>
        public static string Replace_file {
            get {
                return ResourceManager.GetString("Replace_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPA/RPI files.
        /// </summary>
        public static string RPA_RPI_files {
            get {
                return ResourceManager.GetString("RPA_RPI_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save archive.
        /// </summary>
        public static string Save_archive {
            get {
                return ResourceManager.GetString("Save_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed.
        /// </summary>
        public static string Save_failed {
            get {
                return ResourceManager.GetString("Save_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving new archive failed with following error: {0}.
        /// </summary>
        public static string Save_failed_reason {
            get {
                return ResourceManager.GetString("Save_failed_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save RenPy Archive.
        /// </summary>
        public static string Save_RenPy_Archive {
            get {
                return ResourceManager.GetString("Save_RenPy_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving archive....
        /// </summary>
        public static string Saving_archive {
            get {
                return ResourceManager.GetString("Saving_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search next.
        /// </summary>
        public static string Search_next {
            get {
                return ResourceManager.GetString("Search_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file path: .
        /// </summary>
        public static string Selected_file_path {
            get {
                return ResourceManager.GetString("Selected_file_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file size: .
        /// </summary>
        public static string Selected_file_size {
            get {
                return ResourceManager.GetString("Selected_file_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unrpyc script.
        /// </summary>
        public static string UNRPYC_script {
            get {
                return ResourceManager.GetString("UNRPYC_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved files count: .
        /// </summary>
        public static string Unsaved_files_count {
            get {
                return ResourceManager.GetString("Unsaved_files_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file from file list on the side to preview contents. Check and export to save it locally or delete it from archive. Drag and drop files to file list to add new files into archive..
        /// </summary>
        public static string Usage_instructions_loaded {
            get {
                return ResourceManager.GetString("Usage_instructions_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start by creating/loading archive file or drag and drop archive file into this area to load it..
        /// </summary>
        public static string Usage_instructions_new {
            get {
                return ResourceManager.GetString("Usage_instructions_new", resourceCulture);
            }
        }
    }
}
