<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>RPA_Explorer</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>default</LangVersion>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Nullable>disable</Nullable>
    <ApplicationIcon>images\RPA Explorer.ico</ApplicationIcon>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DefineConstants>TRACE;</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DefineConstants>TRACE;</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ArchiveSave.cs" />
    <Compile Remove="ArchiveSave.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft-Windows10-APICodePack-Shell" Version="1.1.8" />
    <PackageReference Include="NeoSmart.PrettySize" Version="2.1.0" />
    <PackageReference Include="System.Resources.Extensions" Version="4.6.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="About.resx" />
    <EmbeddedResource Include="Lang.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Lang.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Include="MainWindow.resx" />
    <EmbeddedResource Include="Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Lang.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Lang.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RPA Parser\RPAParser.csproj" />
  </ItemGroup>

</Project>